
package View.GUI_MenuPrincipal;

import View.GUI_AsignacionProd.Menu_AsignacionProd;
import View.GUI_Departamentos.Menu_Departamentos;
import View.GUI_Precios.Menu_Precios;
import View.GUI_Productos.Menu_Productos;

/**
 *
 * @author alexis
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Menu_Principal() {
        initComponents();
        this.setTitle("Super Mercado UAM-C"); // Titulo de ventana
        this.setLocationRelativeTo(null);   // Para que la ventana aparezca centrada en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        control_Productos = new javax.swing.JButton();
        control_Departamentos = new javax.swing.JButton();
        asignar_Productos = new javax.swing.JButton();
        aisgnar_Precios = new javax.swing.JButton();
        salir_App = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu de opciones");

        control_Productos.setText("Control de Productos");
        control_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_ProductosActionPerformed(evt);
            }
        });

        control_Departamentos.setText("Control de Departamentos");
        control_Departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_DepartamentosActionPerformed(evt);
            }
        });

        asignar_Productos.setText("Asignación de Productos a Departamentos");
        asignar_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignar_ProductosActionPerformed(evt);
            }
        });

        aisgnar_Precios.setText("Asignación de Precios a Productos");
        aisgnar_Precios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aisgnar_PreciosActionPerformed(evt);
            }
        });

        salir_App.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salir.png"))); // NOI18N
        salir_App.setText("Salir");
        salir_App.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_AppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir_App)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(control_Productos)
                    .addComponent(control_Departamentos)
                    .addComponent(aisgnar_Precios)
                    .addComponent(asignar_Productos))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(control_Productos)
                .addGap(18, 18, 18)
                .addComponent(control_Departamentos)
                .addGap(18, 18, 18)
                .addComponent(asignar_Productos)
                .addGap(18, 18, 18)
                .addComponent(aisgnar_Precios)
                .addGap(18, 18, 18)
                .addComponent(salir_App)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_AppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_AppActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salir_AppActionPerformed

    private void control_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_ProductosActionPerformed
        new Menu_Productos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_control_ProductosActionPerformed

    private void control_DepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_DepartamentosActionPerformed
        new Menu_Departamentos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_control_DepartamentosActionPerformed

    private void asignar_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignar_ProductosActionPerformed
        new Menu_AsignacionProd().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_asignar_ProductosActionPerformed

    private void aisgnar_PreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aisgnar_PreciosActionPerformed
        new Menu_Precios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aisgnar_PreciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aisgnar_Precios;
    private javax.swing.JButton asignar_Productos;
    private javax.swing.JButton control_Departamentos;
    private javax.swing.JButton control_Productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salir_App;
    // End of variables declaration//GEN-END:variables
}
