
package View.GUI_AsignacionProd;

import ConectionSQL.*;
import Model.Asignacion;
import javax.swing.JOptionPane;

/**
 *
 * @author alexis
 */
public class Alta_Prod_Depto extends javax.swing.JFrame {
    AsigProd_DB asigProd_db = new AsigProd_DB();
    Deptos_DB depto_db = new Deptos_DB();
    Productos_DB producto_db = new Productos_DB();

    /**
     * Creates new form Alta_Prod_Depto
     */
    public Alta_Prod_Depto() {
        initComponents();
        this.setTitle("Asignación de Productos a Departamentos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        regresar_MenuAsig = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        altaClaveProd = new javax.swing.JTextField();
        altaClaveDepto = new javax.swing.JTextField();
        altaAsigProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alta de un producto en un departamento:");

        regresar_MenuAsig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actualizar.png"))); // NOI18N
        regresar_MenuAsig.setText("Regresar a Menú Asignación de Productos");
        regresar_MenuAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_MenuAsigActionPerformed(evt);
            }
        });

        jLabel2.setText("Clave del producto");

        jLabel3.setText("Clave del departamento");

        altaAsigProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/GuardarTodo.png"))); // NOI18N
        altaAsigProd.setText("Dar de alta");
        altaAsigProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaAsigProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(regresar_MenuAsig))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(altaAsigProd)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(altaClaveDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(altaClaveProd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(altaClaveProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(altaClaveDepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(altaAsigProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(regresar_MenuAsig)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresar_MenuAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_MenuAsigActionPerformed
        new Menu_AsignacionProd().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresar_MenuAsigActionPerformed

    private void altaAsigProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaAsigProdActionPerformed
        double precioInicial = -1;
        boolean banDepto;
        boolean banProd;
        boolean banAsigProd;
        if (!"".equals(altaClaveProd.getText()) && !"".equals(altaClaveDepto.getText())) {
            String clave_depto = altaClaveDepto.getText();
            banDepto = depto_db.buscaDepto(clave_depto);
            if (banDepto) {
                int clave_prod = Integer.parseInt(altaClaveProd.getText());
                banProd = producto_db.buscaProducto(clave_prod);
                if (banProd) {
                    banAsigProd = asigProd_db.buscaProductoDepto(clave_prod);
                    if (banAsigProd) {
                        JOptionPane.showMessageDialog(null, "El producto ya estaba asignado","",JOptionPane.ERROR_MESSAGE);
                    } else {
                        Asignacion a = new Asignacion();
                        a.setClaveProd(clave_prod);
                        a.setPrecio(precioInicial);
                        a.setClaveDepto(clave_depto);
                        asigProd_db.altaAsignacionProducto(a);
                        JOptionPane.showMessageDialog(null, "Se asignó el producto al depto","",JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No existe un producto con esa clave","",JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay depto con la clave proporcionada","",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Porfavor, ingresa toda la información","",JOptionPane.ERROR_MESSAGE);
        }
        altaClaveProd.setText("");
        altaClaveDepto.setText("");
    }//GEN-LAST:event_altaAsigProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta_Prod_Depto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta_Prod_Depto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta_Prod_Depto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta_Prod_Depto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta_Prod_Depto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaAsigProd;
    private javax.swing.JTextField altaClaveDepto;
    private javax.swing.JTextField altaClaveProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton regresar_MenuAsig;
    // End of variables declaration//GEN-END:variables
}
