
package View.GUI_Precios;

import View.GUI_MenuPrincipal.Menu_Principal;

/**
 *
 * @author alexis
 */
public class Menu_Precios extends javax.swing.JFrame {

    /**
     * Creates new form Precios
     */
    public Menu_Precios() {
        initComponents();
        this.setTitle("Asignación de Precios a Productos");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar_Menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        asigPrecio = new javax.swing.JButton();
        verPrecios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresar_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Actualizar.png"))); // NOI18N
        regresar_Menu.setText("Regresar a Menú");
        regresar_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresar_MenuActionPerformed(evt);
            }
        });

        jLabel1.setText("Menú Asignación de Precios");

        asigPrecio.setText("Asignar un Precio a un Producto");
        asigPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asigPrecioActionPerformed(evt);
            }
        });

        verPrecios.setText("Consultar Precios de los Productos de un Departamento");
        verPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPreciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regresar_Menu)
                    .addComponent(jLabel1)
                    .addComponent(verPrecios)
                    .addComponent(asigPrecio))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(asigPrecio)
                .addGap(36, 36, 36)
                .addComponent(verPrecios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(regresar_Menu)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresar_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresar_MenuActionPerformed
        new Menu_Principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresar_MenuActionPerformed

    private void asigPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asigPrecioActionPerformed
        new Asignar_Precios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_asigPrecioActionPerformed

    private void verPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPreciosActionPerformed
        new Consultar_Precios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_verPreciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Precios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Precios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asigPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresar_Menu;
    private javax.swing.JButton verPrecios;
    // End of variables declaration//GEN-END:variables
}
